apiVersion: v1
kind: Secret
metadata:
  name: repository-github-sromerotech-homelab
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:sromerotech/homelab.git
