apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  valuesContent: |-
    configs:
      params:
        server.insecure: true
    global:
      domain: argocd.home
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
