apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  labels:
    app: bind
    namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: bind
          image: ubuntu/bind9:9.18-22.04_beta
          resources: {}
          env:
            - name: BIND9_USER
              value: root
            - name: DOCKER_LOGS
              value: '1'
            - name: ALLOW_QUERY
              value: any
            - name: TZ
              value: UTC
          ports:
            - containerPort: 53
          volumeMounts:
            - name: config
              mountPath: /etc/bind/named.conf
              subPath: named.conf
            - name: config
              mountPath: /etc/bind/home.zone
              subPath: home.zone
      volumes:
        - name: config
          configMap:
            name: bind-cm
            items:
              - key: named.conf
                path: named.conf
              - key: home.zone
                path: home.zone
