apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: dns
spec:
  type: LoadBalancer
  selector:
    app: bind
  ports:
    - name: tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP
