apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-lovelace-climate
data:
  climate.yaml: |
    title: Climate
    views:
      - title: Home
        path: home
        panel: true
        cards:
          - type: vertical-stack
            cards:
              - type: iframe
                url: http://grafana.home/d-solo/home-climate/home-climate?panelId=1&kiosk&theme=dark&refresh=30s
                aspect_ratio: 40%
              - type: iframe
                url: http://grafana.home/d-solo/home-climate/home-climate?panelId=2&kiosk&theme=dark&refresh=30s
                aspect_ratio: 40%
      - title: Extremes
        path: extremes
        panel: true
        cards:
          - type: iframe
            url: http://grafana.home/d/home-climate-extremes/home-climate-extremes?kiosk&theme=dark&refresh=5m
            aspect_ratio: 130%
