apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-prometheus
  namespace: argocd
  labels:
    argocd.sromerotech.home/app: 'true'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 62.3.0
      helm:
        releaseName: my-prometheus
        valuesObject:
          prometheus:
            prometheusSpec:
              retention: 15d
              retentionSize: 30GiB
              enableAdminAPI: false
          grafana:
            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - grafana.home
            persistence:
              enabled: true
              storageClassName: longhorn
              size: 5Gi
          kubeEtcd:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true