apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-influxdb
  namespace: argocd
  labels:
    argocd.sromerotech.home/app: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: 'git@github.com:sromerotech/homelab.git'
    targetRevision: main
    path: argocd/apps/influxdb/chart
    helm:
      releaseName: influxdb
      valueFiles:
        - values.yaml
        - secrets://secrets.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
