apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-file
data:
  configuration.yaml: |
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
        - 10.43.0.0/16
    mobile_app:
    
