apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cloudflare-ddns
  namespace: argocd
  labels:
    argocd.sromerotech.home/app: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cloudflare-scripts
    server: https://kubernetes.default.svc
  source:
    path: argocd/apps/cloudflare-ddns/manifests
    repoURL: 'git@github.com:sromerotech/homelab.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
