---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8123
      targetPort: http
      name: web
    - protocol: TCP
      port: 8124
      targetPort: dns
      name: dns
    - protocol: UDP
      port: 8124
      targetPort: dns-udp
      name: dns-udp
