apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-bind9
  namespace: argocd
  labels:
    argocd.sromerotech.home/app: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dns
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/clusters/home/bind9/manifests
    repoURL: 'git@github.com:sromerotech/homelab.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
