apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: dns
spec:
  type: NodePort
  selector:
    app: bind
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30053
    - port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30053
