apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-longhorn
  namespace: argocd
  labels:
    argocd.sromerotech.home/app: 'true'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.0
      helm:
        releaseName: my-homepage
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.home
          defaultSettings:
            defaultReplicaCount: 1
            backupTarget: s3://sromerotech-homelab-test@eu-south-2/
            backupTargetCredentialSecret: aws-secret
          longhornUI:
            replicas: 1
          csi:
            snapshotterReplicaCount: 1
            resizerReplicaCount: 1
            provisionerReplicaCount: 1
            attacherReplicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true