influxdb2:
    adminUser:
        password: ENC[AES256_GCM,data:FqhhQUdmCW0iDQ==,iv:1YGI+f52Q/HosuewbvXtI/L+26uXtiOlTemAf4EI7Pg=,tag:19ktuRMbPPkDx5vMAdrpbg==,type:str]
        token: ENC[AES256_GCM,data:b9Q3wXJqQdXZuXSzGjkHHn7yyhcwifLBzh44Gol+DUKwWPuPaIMmkZvhgGI=,iv:L08LUla5l6keyzFYbInTHKfqLDCTUvNYrp1cjadU0jU=,tag:umEUWYF3C58lAmDwWCkqHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1husckuuhq6mdvz036xrs2rgrl04hdqyvu7emt5jcph5hfae3fessdc92mk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWHR2Zks0dXVEN2wxNG1i
            YkxYWVdiWjlHKy8rTkhweUU3THdZK0xKMWlrCkpEbkRvNzZkUjhNVHVoSnFVem1z
            emxqWHZ2WXphMHBQSFYwNFZ1bGRpZHcKLS0tIFY4UUhjWEZ6RTA4eTZxMTJsY0M0
            bzFsK2VkWWVIaG04bzc3M0ZSNGNVQWcKmj8uR1aHkVYV4Rjt/bLFlazx76sVjl9k
            Lb20Y36ltOMc4m7kcZIeq2R8Y/FvnjrkqxH0mEv8iZ2i4/X1ALcr/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T22:18:12Z"
    mac: ENC[AES256_GCM,data:RPeLYp7yKBWWOTgSqqxFjnwQSX89AmZ/KZ8PtlFqM3aDNhb973LihB7Ko/WoN8eA+NlzOTNxaOApptTAwpecRVzQaKRF0G3tSvx9Px8i+EFx9CDfpvT/aQsQWO6ASii6ckqDDxamhxUviuFvppI6DO64O88laSOj59e2dqxr0yo=,iv:prmo3zdmn32MGv4f+4zL4CwTCHI7/zP5990X3zpeGWk=,tag:RFOiZyLa2bA0W/KnbQWCLw==,type:str]
    pgp: []
    encrypted_regex: ^(password|token)$
    version: 3.9.4
