grafana:
    adminPassword: ENC[AES256_GCM,data:AkPbxEAJeVCSoA==,iv:VhtQ3wolKcK/5a5saQzWUWDbs+zUnlEPlWc54mbBoOQ=,tag:Hcdx272ZjBjjIzQLTCsvyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1husckuuhq6mdvz036xrs2rgrl04hdqyvu7emt5jcph5hfae3fessdc92mk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUjdnWEE5STlJNytmM0lk
            Mk8zaVZEdnByTjgvd0FNait5WWI3RWE2bVJNCmhaa21jc3pkaTVIMDUxZmlCS3Br
            b1BCTWVmR3p6NXUvUi9VMHZnTkVITzAKLS0tIDZ6V2NjcldKZDFrbTZXaFlmWWlO
            S3cyd2c2aWllMkxWNi9MQVd2TGVJSVEKh31C82uqux814TvwWjELehoX6jeAySDa
            aNeAJig8L6j3ZBV3Q5IIqFzAHUFKtj+feTANCmWr28CguNdMhT3lKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T10:39:26Z"
    mac: ENC[AES256_GCM,data:+f5ooTNukZxgotacoK4J1TecpFpbUUMlcRCp9NxX+PxJM5PQy0U+LR5GrOt+x4mU3bYLdPgGM3U8g1czH8XqkhG0rV1/sdnivwjHPHDKX6xElWNcc/Jnb35TBEtyvSniuIPbmhgUa2cl3oIE5F3a12RWWoUYtzTBBLllXdhzV4I=,iv:KEAbl55R7smLUZULYd86l5aASvgi2c+1E6MwyFT607A=,tag:2LMj1EVwL9Gw/50i3hfI3Q==,type:str]
    pgp: []
    encrypted_regex: ^(password|token|adminPassword)$
    version: 3.9.4
