apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-pihole
  namespace: argocd
  labels:
    argocd.sromerotech.home/app: 'true'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dns
    server: https://kubernetes.default.svc
  source:
    path: argocd/clusters/home/pihole/manifests
    repoURL: 'git@github.com:sromerotech/homelab.git'
    targetRevision: HEAD
    kustomize:
      patches:
        - target:
            kind: Ingress
            name: pihole
          patch: |-
            - op: replace
              path: /spec/rules/0/host
              value: pihole.home
        - target:
            kind: Service
            name: pihole
          patch: |-
            - op: add
              path: /spec/clusterIP
              value: 10.43.228.29
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
